name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: 3.6.3
  SHA256: 243a86649cf6f23eeb6a2ff2456e09e5d77dd9018a54d3d96b0c6bdd6ba6c7f1

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt update
          sudo apt install build-essential
          ./generate.sh "$VERSION" "$SHA256"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Generated"
          draft: false
          name: "Generated"
          tag_name: generated
          files: output/openssl-3.6.3-generated.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
