name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: 4.0.2
  SHA256: 736b467530f916737b7031310ccb21d8218c6229e61e8e160cd1d3458cd543a8

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt update
          sudo apt install build-essential
          ./generate.sh "$VERSION" "$SHA256"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Generated"
          draft: false
          name: "Generated"
          tag_name: generated
          files: output/openssl-4.0.2-generated.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
