name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: 4.0.3
  SHA256: 325b5c806167c13b40b1ffeadfe0248197c00eccc4cf123ec1e28d2d2fd216d9

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt update
          sudo apt install build-essential
          ./generate.sh "$VERSION" "$SHA256"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Generated"
          draft: false
          name: "Generated"
          tag_name: generated
          files: output/openssl-4.0.3-generated.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
